src/Entity/ContenuPanier.php
<?php

namespace App\Entity;

use App\Repository\ContenuPanierRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ContenuPanierRepository::class)]
class ContenuPanier
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'contenuPaniers')]
    private ?Produit $produit = null;

    #[ORM\ManyToOne(inversedBy: 'contenuPaniers')]
    private ?Panier $panier = null;

    #[ORM\Column]
    private ?int $quantite = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_ajout = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProduit(): ?Produit
    {
        return $this->produit;
    }

    public function setProduit(?Produit $produit): static
    {
        $this->produit = $produit;

        return $this;
    }

    public function getPanier(): ?Panier
    {
        return $this->panier;
    }

    public function setPanier(?Panier $panier): static
    {
        $this->panier = $panier;

        return $this;
    }

    public function getQuantite(): ?int
    {
        return $this->quantite;
    }

    public function setQuantite(int $quantite): static
    {
        $this->quantite = $quantite;

        return $this;
    }

    public function getDateAjout(): ?\DateTimeInterface
    {
        return $this->date_ajout;
    }

    public function setDateAjout(\DateTimeInterface $date_ajout): static
    {
        $this->date_ajout = $date_ajout;

        return $this;
    }
}

src/Form/ContenuPanierType.php
<?php

namespace App\Form;

use App\Entity\ContenuPanier;
use App\Entity\Panier;
use App\Entity\Produit;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ContenuPanierType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('quantite')
            ->add('date_ajout')
            ->add('produit', EntityType::class, [
                'class' => Produit::class,
                'choice_label' => 'id',
            ])
            ->add('panier', EntityType::class, [
                'class' => Panier::class,
                'choice_label' => 'id',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => ContenuPanier::class,
        ]);
    }
}

src/Controller/ContenuPanierController.php
<?php

namespace App\Controller;

use App\Entity\ContenuPanier;
use App\Form\ContenuPanierType;
use App\Repository\ContenuPanierRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/{_locale}/contenu')]
class ContenuPanierController extends AbstractController
{
    // Voir les contenus de tous les paniers
    //#[Route('/', name: 'app_contenu_panier_index', methods: ['GET'])]
    public function index(ContenuPanierRepository $contenuPanierRepository): Response
    {
        return $this->render('contenu_panier/index.html.twig', [
            'contenu_paniers' => $contenuPanierRepository->findAll(),
        ]);
    }

    // Nouveau contenu dans le panier
    //#[Route('/new', name: 'app_contenu_panier_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $contenuPanier = new ContenuPanier();
        $form = $this->createForm(ContenuPanierType::class, $contenuPanier);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($contenuPanier);
            $entityManager->flush();

            return $this->redirectToRoute('app_contenu_panier_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('contenu_panier/new.html.twig', [
            'contenu_panier' => $contenuPanier,
            'form' => $form,
        ]);
    }

    // Affichage un contenu panier
    //#[Route('/{id}', name: 'app_contenu_panier_show', methods: ['GET'])]
    public function show(ContenuPanier $contenuPanier): Response
    {
        return $this->render('contenu_panier/show.html.twig', [
            'contenu_panier' => $contenuPanier,
        ]);
    }

    // Edit contenu panier
    //#[Route('/{id}/edit', name: 'app_contenu_panier_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, ContenuPanier $contenuPanier, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ContenuPanierType::class, $contenuPanier);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_contenu_panier_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('contenu_panier/edit.html.twig', [
            'contenu_panier' => $contenuPanier,
            'form' => $form,
        ]);
    }

    // Supprimer un contenu du panier
    //#[Route('/{id}', name: 'app_contenu_panier_delete', methods: ['POST'])]
    public function delete(Request $request, ContenuPanier $contenuPanier, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$contenuPanier->getId(), $request->request->get('_token'))) {
            $entityManager->remove($contenuPanier);
            $entityManager->flush();
        }

        // flash message
        $this->addFlash(
            'success',
            'Produit supprimé du panier.'
        );

        return $this->redirectToRoute('app_panier_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/contenu_panier/_delete_form.html.twig
<form method="post" action="{{ path('app_contenu_panier_delete', {'id': contenu_panier.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ contenu_panier.id) }}">
    <button class="btn btn-danger"><i class="fi fi-rr-trash"></i></button>
</form>

templates/contenu_panier/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit ContenuPanier{% endblock %}

{% block body %}
    <h1>Edit ContenuPanier</h1>

    {{ include('contenu_panier/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_contenu_panier_index') }}">back to list</a>

    {{ include('contenu_panier/_delete_form.html.twig') }}
{% endblock %}

templates/contenu_panier/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}ContenuPanier index{% endblock %}

{% block body %}
    <h1>ContenuPanier index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Quantite</th>
                <th>Date_ajout</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for contenu_panier in contenu_paniers %}
            <tr>
                <td>{{ contenu_panier.id }}</td>
                <td>{{ contenu_panier.quantite }}</td>
                <td>{{ contenu_panier.dateAjout ? contenu_panier.dateAjout|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_contenu_panier_show', {'id': contenu_panier.id}) }}">show</a>
                    <a href="{{ path('app_contenu_panier_edit', {'id': contenu_panier.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_contenu_panier_new') }}">Create new</a>
{% endblock %}

templates/contenu_panier/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New ContenuPanier{% endblock %}

{% block body %}
    <h1>Create new ContenuPanier</h1>

    {{ include('contenu_panier/_form.html.twig') }}

    <a class="btn btn-outline-secondary btn-sm mt-3" href="{{ path('app_contenu_panier_index') }}">back to list</a>
{% endblock %}

templates/contenu_panier/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'contenupanier.title'|trans }}{% endblock %}

{% block body %}
    <h1>{{ 'contenupanier.title'|trans }}</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>{{ 'produit.id'|trans }}</th>
                <td>{{ contenu_panier.id }}</td>
            </tr>
            <tr>
                <th>{{ 'produit.quantity'|trans }}</th>
                <td>{{ contenu_panier.quantite }}</td>
            </tr>
            <tr>
                <th>{{ 'produit.date'|trans }}</th>
                <td>{{ contenu_panier.dateAjout ? contenu_panier.dateAjout|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_contenu_panier_index') }}">back to list</a>

    <a href="{{ path('app_contenu_panier_edit', {'id': contenu_panier.id}) }}">edit</a>

    {{ include('contenu_panier/_delete_form.html.twig') }}
{% endblock %}